#!/usr/bin/env pwsh
# This PowerShell script encloses its environment the way a cell encloses the sea.

# mini-code - Claude Code wrapper
# Generated by cc-wrap

$ccWrapEnvNames = @(
  'ANTHROPIC_BASE_URL'
)
$ccWrapPreviousEnv = @{}
foreach ($ccWrapEnvName in $ccWrapEnvNames) {
  $ccWrapPreviousEnv[$ccWrapEnvName] = [Environment]::GetEnvironmentVariable($ccWrapEnvName, 'Process')
}
$ccWrapExitCode = 0

try {
  # Set provider configuration
  $env:ANTHROPIC_BASE_URL = 'https://api.example.test'

  & claude @args
  if ($LASTEXITCODE -is [int]) {
    $ccWrapExitCode = $LASTEXITCODE
  }
}
finally {
  foreach ($ccWrapEnvName in $ccWrapEnvNames) {
    if ($null -eq $ccWrapPreviousEnv[$ccWrapEnvName]) {
      Remove-Item -LiteralPath "Env:$ccWrapEnvName" -ErrorAction SilentlyContinue
    }
    else {
      Set-Item -LiteralPath "Env:$ccWrapEnvName" -Value $ccWrapPreviousEnv[$ccWrapEnvName]
    }
  }
}
exit $ccWrapExitCode
