#!/usr/bin/env pwsh
# This PowerShell script encloses its environment the way a cell encloses the sea.

# mini-code - Claude Code wrapper
# Generated by cc-wrap

# Set provider configuration
$env:ANTHROPIC_BASE_URL = 'https://api.example.test'

& claude @args
if ($LASTEXITCODE -is [int]) {
  exit $LASTEXITCODE
}
exit 0
