#!/usr/bin/env pwsh
# This PowerShell script encloses its environment the way a cell encloses the sea.

# basic-code - Use Claude Code with Basic API
# Generated by cc-wrap

# Check if BASIC_API_KEY is set
if ([string]::IsNullOrEmpty($env:BASIC_API_KEY)) {
  [Console]::Error.WriteLine('Error: BASIC_API_KEY environment variable is not set')
  [Console]::Error.WriteLine('Please set BASIC_API_KEY, e.g.: $env:BASIC_API_KEY = ''your-api-key''')
  exit 1
}

# Set provider configuration
$env:ANTHROPIC_BASE_URL = 'https://api.example.test/v1'
$env:ANTHROPIC_AUTH_TOKEN = $env:BASIC_API_KEY
$env:ANTHROPIC_MODEL = 'basic-model'
$env:ANTHROPIC_REASONING_MODEL = 'basic-model'
$env:ANTHROPIC_DEFAULT_OPUS_MODEL = 'basic-model'
$env:ANTHROPIC_DEFAULT_SONNET_MODEL = 'basic-model'
$env:ANTHROPIC_DEFAULT_HAIKU_MODEL = 'basic-model'
$env:CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = '1'
$env:CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = '1'
$env:CLAUDE_CONFIG_DIR = $HOME + '/.config/claude-basic'

& claude @args
if ($LASTEXITCODE -is [int]) {
  exit $LASTEXITCODE
}
exit 0
