#!/usr/bin/env pwsh
# This PowerShell script encloses its environment the way a cell encloses the sea.

# glm-code - Use Claude Code with GLM API
# Generated by cc-wrap

# Check if GLM_API_KEY is set
if ([string]::IsNullOrEmpty($env:GLM_API_KEY)) {
  [Console]::Error.WriteLine('Error: GLM_API_KEY environment variable is not set')
  [Console]::Error.WriteLine('Please set GLM_API_KEY, e.g.: $env:GLM_API_KEY = ''your-api-key''')
  exit 1
}

# Set provider configuration
$env:ANTHROPIC_BASE_URL = 'https://open.bigmodel.cn/api/anthropic'
$env:ANTHROPIC_AUTH_TOKEN = $env:GLM_API_KEY
$env:ANTHROPIC_MODEL = 'glm-5'
$env:ANTHROPIC_REASONING_MODEL = 'glm-5'
$env:ANTHROPIC_DEFAULT_OPUS_MODEL = 'glm-5'
$env:ANTHROPIC_DEFAULT_SONNET_MODEL = 'glm-5'
$env:ANTHROPIC_DEFAULT_HAIKU_MODEL = 'glm-5'
$env:CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = '1'
$env:CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = '1'
$env:CLAUDE_CONFIG_DIR = $HOME + '/.config/claude-glm'

& claude @args
if ($LASTEXITCODE -is [int]) {
  exit $LASTEXITCODE
}
exit 0
