#!/usr/bin/env pwsh
# This PowerShell script encloses its environment the way a cell encloses the sea.

# or-code - Use Claude Code with OpenRouter API
# Generated by cc-wrap

# Check if OPENROUTER_API_KEY is set
if ([string]::IsNullOrEmpty($env:OPENROUTER_API_KEY)) {
  [Console]::Error.WriteLine('Error: OPENROUTER_API_KEY environment variable is not set')
  [Console]::Error.WriteLine('Please set OPENROUTER_API_KEY, e.g.: $env:OPENROUTER_API_KEY = ''your-api-key''')
  exit 1
}

# Set provider configuration
$env:ANTHROPIC_BASE_URL = 'https://openrouter.ai/api/v1'
$env:ANTHROPIC_AUTH_TOKEN = $env:OPENROUTER_API_KEY
$env:ANTHROPIC_MODEL = 'anthropic/claude-sonnet-4.6'
$env:ANTHROPIC_REASONING_MODEL = 'anthropic/claude-sonnet-4.6'
$env:ANTHROPIC_DEFAULT_OPUS_MODEL = 'anthropic/claude-opus-4.6'
$env:ANTHROPIC_DEFAULT_SONNET_MODEL = 'anthropic/claude-sonnet-4.6'
$env:ANTHROPIC_DEFAULT_HAIKU_MODEL = 'anthropic/claude-haiku-4.5'
$env:CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = '1'
$env:CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = '1'

& claude @args
if ($LASTEXITCODE -is [int]) {
  exit $LASTEXITCODE
}
exit 0
