#!/bin/bash

render_wrapper_script() {
  local provider_json="$1"
  local disable_nonessential_traffic="$2"
  local experimental_agent_teams="$3"
  local script_name description required_var config_dir config_dir_value

  script_name="$(jq -r '.script_name' <<<"$provider_json")"
  description="$(jq -r '.description // empty' <<<"$provider_json")"
  required_var="$(jq -r '.required_env.var // empty' <<<"$provider_json")"
  config_dir="$(jq -r '.config_dir // empty' <<<"$provider_json")"

  printf '#!/bin/bash\n'
  printf '# %s\n\n' "$CC_WRAP_GENERATED_SCRIPT_SIGNATURE"

  if [[ -n "$description" ]]; then
    printf '# %s - %s\n' "$script_name" "$description"
  else
    printf '# %s - Claude Code wrapper\n' "$script_name"
  fi
  printf '# Generated by cc-wrap\n\n'

  if [[ -n "$required_var" ]]; then
    printf '# Check if %s is set\n' "$required_var"
    printf 'if [[ -z "${%s:-}" ]]; then\n' "$required_var"
    printf '  echo "Error: %s environment variable is not set" >&2\n' "$required_var"
    printf '  echo "Please set %s, e.g.: export %s='\''your-api-key'\''" >&2\n' "$required_var" "$required_var"
    printf '  exit 1\n'
    printf 'fi\n\n'
  fi

  printf '# Set provider configuration\n'
  while IFS= read -r env_entry; do
    local env_key env_value
    env_key="$(jq -r '.key' <<<"$env_entry")"
    env_value="$(jq -r '.value' <<<"$env_entry")"
    printf 'export %s=%s\n' "$env_key" "$(quote_export_value "$env_value")"
  done < <(jq -c '.env | to_entries[]' <<<"$provider_json")

  if provider_has_value '.models' "$provider_json"; then
    render_models_block "$provider_json"
  fi

  if [[ "$disable_nonessential_traffic" == "true" ]]; then
    printf 'export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1\n'
  fi

  if [[ "$experimental_agent_teams" == "true" ]]; then
    printf 'export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1\n'
  fi

  if [[ -n "$config_dir" ]]; then
    config_dir_value="$(path_for_generated_script "$config_dir")"
    printf 'export CLAUDE_CONFIG_DIR=%s\n' "$(quote_export_value "$config_dir_value")"
  fi

  printf '\nexec claude "$@"\n'
}

render_models_block() {
  local provider_json="$1"
  local models_type

  models_type="$(jq -r '.models | type' <<<"$provider_json")"

  if [[ "$models_type" == "string" ]]; then
    local model_value
    model_value="$(jq -r '.models' <<<"$provider_json")"
    printf 'export ANTHROPIC_MODEL=%s\n' "$(quote_export_value "$model_value")"
    printf 'export ANTHROPIC_REASONING_MODEL=%s\n' "$(quote_export_value "$model_value")"
    printf 'export ANTHROPIC_DEFAULT_OPUS_MODEL=%s\n' "$(quote_export_value "$model_value")"
    printf 'export ANTHROPIC_DEFAULT_SONNET_MODEL=%s\n' "$(quote_export_value "$model_value")"
    printf 'export ANTHROPIC_DEFAULT_HAIKU_MODEL=%s\n' "$(quote_export_value "$model_value")"
    return
  fi

  while IFS= read -r model_entry; do
    local model_key model_value model_env_name
    model_key="$(jq -r '.key' <<<"$model_entry")"
    model_value="$(jq -r '.value' <<<"$model_entry")"

    case "$model_key" in
      default)
        model_env_name="ANTHROPIC_MODEL"
        ;;
      reasoning)
        model_env_name="ANTHROPIC_REASONING_MODEL"
        ;;
      opus)
        model_env_name="ANTHROPIC_DEFAULT_OPUS_MODEL"
        ;;
      sonnet)
        model_env_name="ANTHROPIC_DEFAULT_SONNET_MODEL"
        ;;
      haiku)
        model_env_name="ANTHROPIC_DEFAULT_HAIKU_MODEL"
        ;;
      *)
        continue
        ;;
    esac

    printf 'export %s=%s\n' "$model_env_name" "$(quote_export_value "$model_value")"
  done < <(jq -c '.models | to_entries[]' <<<"$provider_json")
}
